#!/usr/bin/env python3
"""
Generate data/production_order.json — the canonical order in which the Bible
should be translated, per GENRES.md.

This is a build-time script. Run it once to (re)generate the order file.
The runtime resolver (next_chapter.py) reads the JSON.

Order rationale: SIL/Wycliffe-style complexity progression. Narrative first
(builds vocabulary), Pauline corpus as a block (theological coherence),
general epistles, Revelation (after symbol/vision check infrastructure),
then OT in phase 6+.
"""
import json
from pathlib import Path

# NT chapter counts (verified against SBLGNT)
NT_CHAPTERS = {
    "MAT": 28, "MRK": 16, "LUK": 24, "JHN": 21, "ACT": 28,
    "ROM": 16, "1CO": 16, "2CO": 13, "GAL": 6, "EPH": 6, "PHP": 4, "COL": 4,
    "1TH": 5, "2TH": 3, "1TI": 6, "2TI": 4, "TIT": 3, "PHM": 1,
    "HEB": 13, "JAS": 5, "1PE": 5, "2PE": 3,
    "1JN": 5, "2JN": 1, "3JN": 1, "JUD": 1, "REV": 22,
}

# Order of books (per GENRES.md production plan)
PHASES = [
    {
        "name": "Phase 2 — NT narrative",
        "books": ["MRK", "MAT", "LUK", "ACT", "JHN"],
    },
    {
        "name": "Phase 3 — Pauline corpus (composition order)",
        "books": ["GAL", "1TH", "2TH", "1CO", "2CO", "ROM", "PHM", "PHP",
                  "COL", "EPH", "1TI", "2TI", "TIT"],
    },
    {
        "name": "Phase 4 — General epistles + Hebrews",
        "books": ["JAS", "1PE", "2PE", "1JN", "2JN", "3JN", "JUD", "HEB"],
    },
    {
        "name": "Phase 5 — Revelation (after apocalyptic checks built)",
        "books": ["REV"],
    },
]


def main():
    order = []
    for phase in PHASES:
        for book in phase["books"]:
            chapters = NT_CHAPTERS[book]
            for ch in range(1, chapters + 1):
                order.append({
                    "book": book,
                    "chapter": ch,
                    "phase": phase["name"],
                })

    out = {
        "_note": "Auto-generated by build_production_order.py based on GENRES.md.",
        "_total_chapters": len(order),
        "_phases": [p["name"] for p in PHASES],
        "order": order,
    }

    out_path = Path(__file__).resolve().parent.parent / "data" / "production_order.json"
    out_path.write_text(json.dumps(out, indent=2), encoding="utf-8")
    print(f"Wrote {out_path}")
    print(f"  Total chapters in NT production order: {len(order)}")


if __name__ == "__main__":
    main()
