#!/usr/bin/env python3
"""
End-of-book EXTERNAL AI REVIEW status — the single source of truth for the backlog.

A book's end-of-book external review is "done" when a *response* doc has been
committed to its `docs/end_of_book/<book>/` directory. The flow per book is:

    external_review_items_<BOOK>.md      (flagged items)
    external_review_packet_<BOOK>_*.md   (the packet you paste into Gemini/ChatGPT)
    <something with "response" in name>  (the worked-through outcome — DONE marker)

A book is PENDING when it has a packet but no response file yet.

Usage:
    python3 scripts/external_review_status.py            # print summary + (re)write QUEUE.md
    python3 scripts/external_review_status.py --no-write  # print only, don't touch QUEUE.md

QUEUE.md (written to docs/end_of_book/_external_inbox/) is the ordered work list
the Cowork browser agent follows — oldest debt first, with the exact public URL of
each packet to copy. Re-run this after responses land to shrink the queue.
"""
import argparse
import re
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
EOB = ROOT / "docs" / "end_of_book"
INBOX = EOB / "_external_inbox"
QUEUE = INBOX / "QUEUE.md"

RAW_BASE = "https://raw.githubusercontent.com/btwinguitarists/eremos-translation/main"
BLOB_BASE = "https://github.com/btwinguitarists/eremos-translation/blob/main"

PACKET_RE = re.compile(r"external_review_packet_([A-Z0-9]+)_(\d{4}-\d{2}-\d{2})\.md$")


def book_state(book_dir: Path):
    """Return (code, packet_path, packet_date) for the newest packet, or None."""
    packets = []
    for f in book_dir.glob("external_review_packet_*.md"):
        m = PACKET_RE.search(f.name)
        if m:
            packets.append((m.group(2), m.group(1), f))  # (date, code, path)
    if not packets:
        return None
    packets.sort()  # by date string
    pkt_date, code, pkt_path = packets[-1]
    return code, pkt_path, pkt_date


def has_response(book_dir: Path) -> bool:
    """A committed file whose name contains 'response' marks the review done."""
    return any("response" in f.name.lower() for f in book_dir.glob("*.md"))


def scan():
    done, pending = [], []
    for d in sorted(EOB.iterdir()):
        if not d.is_dir() or d.name.startswith("_"):
            continue
        st = book_state(d)
        if st is None:
            continue  # no packet yet — not ready for external review
        code, pkt_path, pkt_date = st
        rec = {"slug": d.name, "code": code, "date": pkt_date,
               "relpath": str(pkt_path.relative_to(ROOT))}
        (done if has_response(d) else pending).append(rec)
    pending.sort(key=lambda r: r["date"])
    done.sort(key=lambda r: r["date"])
    return done, pending


def write_queue(pending):
    INBOX.mkdir(parents=True, exist_ok=True)
    lines = [
        "# External AI review — WORK QUEUE",
        "",
        f"_Auto-generated by `scripts/external_review_status.py` on {date.today()}._",
        "_Re-run that script to refresh after responses land._",
        "",
        f"**{len(pending)} books pending** (oldest debt first). Work top to bottom.",
        "",
        "For each book: open the packet URL, copy the **whole** document, paste into "
        "Gemini and ChatGPT, then commit the combined replies to "
        "`docs/end_of_book/_external_inbox/<CODE>_raw.md`. "
        "Full steps: `docs/COWORK_EXTERNAL_REVIEW_INSTRUCTIONS.md`.",
        "",
    ]
    for i, r in enumerate(pending, 1):
        title = r["slug"].replace("_", " ").title()
        lines += [
            f"### {i}. {title}  (`{r['code']}`)  — packet {r['date']}",
            f"- **Copy this:** {RAW_BASE}/{r['relpath']}",
            f"- (human-readable view: {BLOB_BASE}/{r['relpath']})",
            f"- **Save replies to:** `docs/end_of_book/_external_inbox/{r['code']}_raw.md`",
            "- [ ] Gemini done   - [ ] ChatGPT done   - [ ] committed",
            "",
        ]
    QUEUE.write_text("\n".join(lines))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--no-write", action="store_true", help="print only; don't write QUEUE.md")
    args = ap.parse_args()

    done, pending = scan()
    print("=== End-of-book external AI review — status ===")
    print(f"Done:    {len(done)}")
    print(f"Pending: {len(pending)}")
    print()
    if pending:
        print("PENDING (oldest first):")
        for r in pending:
            print(f"  {r['date']}  {r['code']:<4} {r['slug']}")
    else:
        print("No pending external reviews. Backlog clear.")

    if not args.no_write:
        write_queue(pending)
        print(f"\nWrote {QUEUE.relative_to(ROOT)}  ({len(pending)} books).")


if __name__ == "__main__":
    main()
