#!/usr/bin/env python3
"""
Generate HASHES.md — a verification manifest for every translation file.

Anyone (a reader, a downstream app, an SIL reviewer, a future YOU) can
compute the SHA-256 of `output/translations/<slug>_<NN>.json` and verify it
against this manifest to confirm they have the canonical Eremos Translation
of that chapter.

Combined with GPG-signed commits, this gives you a strong verification chain:
  1. The repo's git history is signed by Ben's GPG key (proves authorship)
  2. HASHES.md lists the SHA-256 of every translation file (proves content)
  3. Anyone can recompute and verify both

Run as part of ship_chapter.sh after any translation file changes.

Usage:
  python3 scripts/update_hashes.py          # write HASHES.md
  python3 scripts/update_hashes.py --check  # verify without writing (CI gate)
"""
import argparse
import hashlib
import json
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TRANSLATIONS = ROOT / "output" / "translations"
HASHES_PATH = ROOT / "HASHES.md"


def file_sha256(path: Path) -> str:
    h = hashlib.sha256()
    h.update(path.read_bytes())
    return h.hexdigest()


def last_commit_for_file(path: Path) -> str | None:
    """Return short commit SHA where this file was last touched."""
    try:
        result = subprocess.run(
            ["git", "log", "-1", "--format=%h", "--", str(path)],
            cwd=ROOT, capture_output=True, text=True, check=True,
        )
        sha = result.stdout.strip()
        return sha if sha else None
    except subprocess.CalledProcessError:
        return None


def collect_files() -> list[dict]:
    entries = []
    for f in sorted(TRANSLATIONS.glob("*_*.json")):
        if "_demo" in f.name:
            continue
        try:
            verses = json.loads(f.read_text(encoding="utf-8"))
            verse_count = len(verses) if isinstance(verses, list) else 0
        except Exception:
            verse_count = 0
        entries.append({
            "path": f"output/translations/{f.name}",
            "sha256": file_sha256(f),
            "verses": verse_count,
            "size_bytes": f.stat().st_size,
            "last_commit": last_commit_for_file(f),
        })
    return entries


def render_markdown(entries: list[dict]) -> str:
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    total_verses = sum(e["verses"] for e in entries)

    lines = [
        "# Eremos Translation — chapter verification manifest",
        "",
        "Cryptographic SHA-256 fingerprints for every translated chapter.",
        "Combined with GPG-signed commits, anyone can verify they have the canonical version.",
        "",
        f"_Generated: {timestamp}_",
        f"_Total chapters: {len(entries)} · Total verses: {total_verses}_",
        "",
        "## How to verify a chapter",
        "",
        "```bash",
        "# Compute the SHA-256 of any translation file:",
        "shasum -a 256 output/translations/mark_06.json",
        "",
        "# Compare against the entry in this file. If they match, you have the canonical version.",
        "```",
        "",
        "## Manifest",
        "",
        "| File | Verses | SHA-256 | Last commit |",
        "|------|--------|---------|-------------|",
    ]
    for e in entries:
        commit = e["last_commit"] or "—"
        lines.append(
            f"| `{e['path']}` | {e['verses']} | `{e['sha256']}` | `{commit}` |"
        )

    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("This manifest is auto-generated by `scripts/update_hashes.py` and updated as part of every chapter ship via `scripts/ship_chapter.sh`.")
    return "\n".join(lines)


def verify(entries: list[dict]) -> tuple[bool, list[str]]:
    """If HASHES.md exists, verify all entries match what's currently on disk."""
    if not HASHES_PATH.exists():
        return False, ["HASHES.md does not exist yet"]

    text = HASHES_PATH.read_text(encoding="utf-8")
    # Extract entries from markdown table
    pattern = re.compile(r"`(output/translations/[^`]+)`\s*\|\s*\d+\s*\|\s*`([a-f0-9]{64})`")
    recorded = {m.group(1): m.group(2) for m in pattern.finditer(text)}

    mismatches = []
    for e in entries:
        rec = recorded.get(e["path"])
        if rec is None:
            mismatches.append(f"NEW: {e['path']} (not in HASHES.md)")
        elif rec != e["sha256"]:
            mismatches.append(f"MISMATCH: {e['path']} (HASHES.md={rec[:12]}…, actual={e['sha256'][:12]}…)")

    for path in recorded:
        if not any(e["path"] == path for e in entries):
            mismatches.append(f"REMOVED: {path} (in HASHES.md but file missing)")

    return (len(mismatches) == 0), mismatches


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="Verify HASHES.md matches current files; exit 1 on mismatch")
    args = parser.parse_args()

    entries = collect_files()

    if args.check:
        ok, mismatches = verify(entries)
        if ok:
            print(f"✓ HASHES.md verified — {len(entries)} chapters all match.")
            return 0
        print(f"✗ HASHES.md verification failed:")
        for m in mismatches:
            print(f"  {m}")
        return 1

    md = render_markdown(entries)
    HASHES_PATH.write_text(md, encoding="utf-8")
    total_verses = sum(e["verses"] for e in entries)
    print(f"Wrote {HASHES_PATH}")
    print(f"  {len(entries)} chapters · {total_verses} verses · all SHA-256 fingerprints recorded")
    return 0


if __name__ == "__main__":
    sys.exit(main())
